export const tabela = [
  {
    numeroAtomico: 1,
    simbolo: 'H',
    elemento: 'Hidrogenio',
    massaAtomico: '1,008',
    fusao: '-259,14',
    ebulicao: '-252,87',
  },
  {
    numeroAtomico: 2,
    simbolo: 'He',
    elemento: 'Helio',
    massaAtomico: '4,0026',
    fusao: '-272,2',
    ebulicao: '-268,9',
  },
  {
    numeroAtomico: 3,
    simbolo: 'Li',
    elemento: 'Lítio',
    massaAtomico: '6,941',
    fusao: '180,5',
    ebulicao: '1342,0',
  },
  {
    numeroAtomico: 4,
    simbolo: 'Be',
    elemento: 'Berílio',
    massaAtomico: '9,0122',
    fusao: '1278,0',
    ebulicao: '2970,0',
  },
  {
    numeroAtomico: 5,
    simbolo: 'B',
    elemento: 'Boro',
    massaAtomico: '10,81',
    fusao: '2075,8',
    ebulicao: '3926,8',
  },
  {
    numeroAtomico: 6,
    simbolo: 'C',
    elemento: 'Carbono',
    massaAtomico: '12,001',
    fusao: '3550,0',
    ebulicao: '4827,0',
  },
  {
    numeroAtomico: 7,
    simbolo: 'N',
    elemento: 'Nitrogênio',
    massaAtomico: '14,004',
    fusao: '-209,9',
    ebulicao: '-195,8',
  },
  {
    numeroAtomico: 8,
    simbolo: 'O',
    elemento: 'Oxigênio',
    massaAtomico: '15,999',
    fusao: '-218,79',
    ebulicao: '-182,96',
  },
  {
    numeroAtomico: 9,
    simbolo: 'F',
    elemento: 'Flúor',
    massaAtomico: '18,998',
    fusao: '-219,67',
    ebulicao: '-188,11',
  },
  {
    numeroAtomico: 10,
    simbolo: 'Ne',
    elemento: 'Neónio',
    massaAtomico: '20,180',
    fusao: '-248,67',
    ebulicao: '-246,05',
  },
  {
    numeroAtomico: 11,
    simbolo: 'Na',
    elemento: 'Sódio',
    massaAtomico: '22,990',
    fusao: '97,8',
    ebulicao: '882,94',
  },
  {
    numeroAtomico: 12,
    simbolo: 'Mg',
    elemento: 'Magnésio',
    massaAtomico: '24,305',
    fusao: '650,0',
    ebulicao: '1090,0',
  },
  {
    numeroAtomico: 13,
    simbolo: 'Ai',
    elemento: 'Alumínio',
    massaAtomico: '26,982',
    fusao: '650,0',
    ebulicao: '2518,82',
  },
  {
    numeroAtomico: 14,
    simbolo: 'Si',
    elemento: 'Silício',
    massaAtomico: '28,085',
    fusao: '1414,85',
    ebulicao: '3265,0',
  },
  {
    numeroAtomico: 15,
    simbolo: 'P',
    elemento: 'Fósforo',
    massaAtomico: '30,974',
    fusao: '44,15',
    ebulicao: '280,5',
  },
  {
    numeroAtomico: 16,
    simbolo: 'S',
    elemento: 'Enxofre',
    massaAtomico: '30,06',
    fusao: '112,8',
    ebulicao: '444,67',
  },
  {
    numeroAtomico: 17,
    simbolo: 'Cl',
    elemento: 'Cloro',
    massaAtomico: '30,45',
    fusao: '-100,98',
    ebulicao: '-34,6',
  },
  {
    numeroAtomico: 18,
    simbolo: 'Ar',
    elemento: 'Argónio',
    massaAtomico: '39,948',
    fusao: '-189,34',
    ebulicao: '-185,85',
  },
  {
    numeroAtomico: 19,
    simbolo: 'K',
    elemento: 'Potássio',
    massaAtomico: '39,098',
    fusao: '63,38',
    ebulicao: '758,8',
  },
  {
    numeroAtomico: 20,
    simbolo: 'Ca',
    elemento: 'Cálcio',
    massaAtomico: '40,078',
    fusao: '842,0',
    ebulicao: '1484,0',
  },
  {
    numeroAtomico: 21,
    simbolo: 'Sc',
    elemento: 'Escândio',
    massaAtomico: '44,956',
    fusao: '1541,0',
    ebulicao: '2836,0',
  },
  {
    numeroAtomico: 22,
    simbolo: 'Ti',
    elemento: 'Titânio',
    massaAtomico: '47,867',
    fusao: '1660,0',
    ebulicao: '3287,0',
  },
  {
    numeroAtomico: 23,
    simbolo: 'V',
    elemento: 'Vanádio',
    massaAtomico: '50,942',
    fusao: '1910,0',
    ebulicao: '3407,0',
  },
  {
    numeroAtomico: 24,
    simbolo: 'Cr',
    elemento: 'Cromo',
    massaAtomico: '51,996',
    fusao: '1907,0',
    ebulicao: '2672,0',
  },
  {
    numeroAtomico: 25,
    simbolo: 'Mn',
    elemento: 'Manganês',
    massaAtomico: '54,938',
    fusao: '1245,0',
    ebulicao: '2061,0',
  },
  {
    numeroAtomico: 26,
    simbolo: 'Fe',
    elemento: 'Ferro',
    massaAtomico: '55,845',
    fusao: '1539,0',
    ebulicao: '2862,0',
  },
  {
    numeroAtomico: 27,
    simbolo: 'Co',
    elemento: 'Cobalto',
    massaAtomico: '58,933',
    fusao: '1493,0',
    ebulicao: '2870,0',
  },
  {
    numeroAtomico: 28,
    simbolo: 'Co',
    elemento: 'Níquel',
    massaAtomico: '58,933',
    fusao: '1493,0',
    ebulicao: '2870,0',
  },
  {
    numeroAtomico: 29,
    simbolo: 'Cu',
    elemento: 'Cobre',
    massaAtomico: '63,546',
    fusao: '1083,0',
    ebulicao: '2567,0',
  },
  {
    numeroAtomico: 30,
    simbolo: 'Zn',
    elemento: 'Zinco',
    massaAtomico: '65,38',
    fusao: '420,58',
    ebulicao: '907,0',
  },
  {
    numeroAtomico: 31,
    simbolo: 'Ga',
    elemento: 'Gálio',
    massaAtomico: '69,723',
    fusao: '29,76',
    ebulicao: '2204,0',
  },
  {
    numeroAtomico: 32,
    simbolo: 'Ge',
    elemento: 'Germânio',
    massaAtomico: '72,610',
    fusao: '938,25',
    ebulicao: '2023,0',
  },
  {
    numeroAtomico: 33,
    simbolo: 'As',
    elemento: 'Arsênio',
    massaAtomico: '74,922',
    fusao: '817,0',
    ebulicao: '613,0',
  },
  {
    numeroAtomico: 34,
    simbolo: 'Se',
    elemento: 'Selênio',
    massaAtomico: '78,960',
    fusao: '221,0',
    ebulicao: '685,0',
  },
  {
    numeroAtomico: 35,
    simbolo: 'Br',
    elemento: 'Bromo',
    massaAtomico: '79,904',
    fusao: '-7,2',
    ebulicao: '59,0',
  },
  {
    numeroAtomico: 36,
    simbolo: 'Kr',
    elemento: 'Kriptônio',
    massaAtomico: '83,798',
    fusao: '-157,2',
    ebulicao: '-153,2',
  },
  {
    numeroAtomico: 37,
    simbolo: 'Rb',
    elemento: 'Rubídio',
    massaAtomico: '85,468',
    fusao: '39,30',
    ebulicao: '688,0',
  },
  {
    numeroAtomico: 38,
    simbolo: 'Sr',
    elemento: 'Estrôncio',
    massaAtomico: '87,620',
    fusao: '769,0',
    ebulicao: '1384,0',
  },
  {
    numeroAtomico: 39,
    simbolo: 'Y',
    elemento: 'Itrio',
    massaAtomico: '88,906',
    fusao: '1522,0',
    ebulicao: '3337,0',
  },
  {
    numeroAtomico: 40,
    simbolo: 'Zr',
    elemento: 'Zircônio',
    massaAtomico: '91,224',
    fusao: '1852,0',
    ebulicao: '4377,0',
  },
  {
    numeroAtomico: 41,
    simbolo: 'Nb',
    elemento: 'Nióbio',
    massaAtomico: '92,906',
    fusao: '2477,0',
    ebulicao: '4744,0',
  },
  {
    numeroAtomico: 42,
    simbolo: 'Mo',
    elemento: 'Molibdênio',
    massaAtomico: '95,940',
    fusao: '2617,0',
    ebulicao: '4612,0',
  },
  {
    numeroAtomico: 43,
    simbolo: 'Tc',
    elemento: 'Tecnécio',
    massaAtomico: '(98)',
    fusao: '2157,0',
    ebulicao: '4265,0',
  },
  {
    numeroAtomico: 44,
    simbolo: 'Ru',
    elemento: 'Rutênio',
    massaAtomico: '101,1',
    fusao: '2250,0',
    ebulicao: '3900,0',
  },
  {
    numeroAtomico: 45,
    simbolo: 'Rh',
    elemento: 'Ródio',
    massaAtomico: '102,905',
    fusao: '1966,0',
    ebulicao: '3727,0',
  },
  {
    numeroAtomico: 46,
    simbolo: 'Pd',
    elemento: 'Paládio',
    massaAtomico: '106,42',
    fusao: '1552,0',
    ebulicao: '2927,0',
  },
  {
    numeroAtomico: 47,
    simbolo: 'Ag',
    elemento: 'Prata',
    massaAtomico: '107,868',
    fusao: '962,0',
    ebulicao: '2212,0',
  },
  {
    numeroAtomico: 48,
    simbolo: 'Cd',
    elemento: 'Cádmio',
    massaAtomico: '112,411',
    fusao: '321,0',
    ebulicao: '765,0',
  },
  {
    numeroAtomico: 49,
    simbolo: 'In',
    elemento: 'Indio',
    massaAtomico: '114,818',
    fusao: '429,7',
    ebulicao: '2345,0',
  },
  {
    numeroAtomico: 50,
    simbolo: 'Sn',
    elemento: 'Estanho',
    massaAtomico: '118,710',
    fusao: '505,0',
    ebulicao: '2875,0',
  },
  {
    numeroAtomico: 51,
    simbolo: 'Sb',
    elemento: 'Antimônio',
    massaAtomico: '121,760',
    fusao: '904,0',
    ebulicao: '1860,0',
  },
  {
    numeroAtomico: 52,
    simbolo: 'Te',
    elemento: 'Telúrio',
    massaAtomico: '127,60',
    fusao: '722,0',
    ebulicao: '1261,0',
  },
  {
    numeroAtomico: 53,
    simbolo: 'I',
    elemento: 'Iodo',
    massaAtomico: '126,90447',
    fusao: '113,5',
    ebulicao: '184,3',
  },
  {
    numeroAtomico: 54,
    simbolo: 'Xe',
    elemento: 'Xenônio',
    massaAtomico: '131,293',
    fusao: '161,4',
    ebulicao: '165,1',
  },
  {
    numeroAtomico: 55,
    simbolo: 'Cs',
    elemento: 'Césio',
    massaAtomico: '132,905',
    fusao: '28,5',
    ebulicao: '672,0',
  },
  {
    numeroAtomico: 56,
    simbolo: 'Ba',
    elemento: 'Bário',
    massaAtomico: '137,327',
    fusao: '725,0',
    ebulicao: '1140,0',
  },
  {
    numeroAtomico: 57,
    simbolo: 'La',
    elemento: 'Lantânio',
    massaAtomico: '138,905',
    fusao: '920,0',
    ebulicao: '3469,0',
  },
  {
    numeroAtomico: 58,
    simbolo: 'Ce',
    elemento: 'Cério',
    massaAtomico: '140,116',
    fusao: '798,0',
    ebulicao: '3443,0',
  },
  {
    numeroAtomico: 59,
    simbolo: 'Pr',
    elemento: 'Praseodímio',
    massaAtomico: '140,908',
    fusao: '935,0',
    ebulicao: '3130,0',
  },
  {
    numeroAtomico: 60,
    simbolo: 'Nd',
    elemento: 'Neodímio',
    massaAtomico: '144,242',
    fusao: '1010,0',
    ebulicao: '3074,0',
  },
  {
    numeroAtomico: 61,
    simbolo: 'Pm',
    elemento: 'Promécio',
    massaAtomico: '145,0',
    fusao: '1100,0',
    ebulicao: '3000,0',
  },
  {
    numeroAtomico: 62,
    simbolo: 'Sm',
    elemento: 'Samário',
    massaAtomico: '150,36',
    fusao: '1072,0',
    ebulicao: '1900,0',
  },
  {
    numeroAtomico: 63,
    simbolo: 'Eu',
    elemento: 'Európio',
    massaAtomico: '151,964',
    fusao: '822,0',
    ebulicao: '1527,0',
  },
  {
    numeroAtomico: 64,
    simbolo: 'Gd',
    elemento: 'Gadolínio',
    massaAtomico: '157,25',
    fusao: '1313,0',
    ebulicao: '3233,0',
  },
  {
    numeroAtomico: 65,
    simbolo: 'Tb',
    elemento: 'Terbium',
    massaAtomico: '158,925',
    fusao: '1356,0',
    ebulicao: '3230,0',
  },
  {
    numeroAtomico: 66,
    simbolo: 'Dy',
    elemento: 'Disprosium',
    massaAtomico: '162,5',
    fusao: '1412,0',
    ebulicao: '2562,0',
  },
  {
    numeroAtomico: 67,
    simbolo: 'Ho',
    elemento: 'Holmium',
    massaAtomico: '164,930',
    fusao: '1474,0',
    ebulicao: '2720,0',
  },
  {
    numeroAtomico: 68,
    simbolo: 'Er',
    elemento: 'Erbium',
    massaAtomico: '167,259',
    fusao: '1529,0',
    ebulicao: '2868,0',
  },
  {
    numeroAtomico: 69,
    simbolo: 'Tm',
    elemento: 'Thulium',
    massaAtomico: '168,934',
    fusao: '1545,0',
    ebulicao: '1950,0',
  },
  {
    numeroAtomico: 70,
    simbolo: 'Yb',
    elemento: 'Ytterbium',
    massaAtomico: '173,054',
    fusao: '824,0',
    ebulicao: '1466,0',
  },
  {
    numeroAtomico: 71,
    simbolo: 'Lu',
    elemento: 'Lutetium',
    massaAtomico: '174,967',
    fusao: '1657,0',
    ebulicao: '3315,0',
  },
  {
    numeroAtomico: 72,
    simbolo: 'Hf',
    elemento: 'Hafnium',
    massaAtomico: '178,49',
    fusao: '2150,0',
    ebulicao: '5400,0',
  },
  {
    numeroAtomico: 73,
    simbolo: 'Ta',
    elemento: 'Tantalum',
    massaAtomico: '180,948',
    fusao: '3017,0',
    ebulicao: '5458,0',
  },
  {
    numeroAtomico: 74,
    simbolo: 'W',
    elemento: 'Tungsten',
    massaAtomico: '183,84',
    fusao: '3422,0',
    ebulicao: '5660,0',
  },
  {
    numeroAtomico: 75,
    simbolo: 'Re',
    elemento: 'Rhenium',
    massaAtomico: '186,207',
    fusao: '3186,0',
    ebulicao: '5627,0',
  },
  {
    numeroAtomico: 76,
    simbolo: 'Os',
    elemento: 'Osmium',
    massaAtomico: '190,23',
    fusao: '3045,0',
    ebulicao: '5027,0',
  },
  {
    numeroAtomico: 77,
    simbolo: 'Ir',
    elemento: 'Iridium',
    massaAtomico: '192,217',
    fusao: '2466,0',
    ebulicao: '4427,0',
  },
  {
    numeroAtomico: 78,
    simbolo: 'Pt',
    elemento: 'Platinum',
    massaAtomico: '195,084',
    fusao: '1768,3',
    ebulicao: '3827,0',
  },
  {
    numeroAtomico: 79,
    simbolo: 'Au',
    elemento: 'Gold',
    massaAtomico: '197,0',
    fusao: '1064,2',
    ebulicao: '3080,0',
  },
  {
    numeroAtomico: 80,
    simbolo: 'Hg',
    elemento: 'Mercury',
    massaAtomico: '200,59',
    fusao: '-38,83',
    ebulicao: '356,6',
  },
  {
    numeroAtomico: 81,
    simbolo: 'Tl',
    elemento: 'Thallium',
    massaAtomico: '204,38',
    fusao: '303,5',
    ebulicao: '1457,0',
  },
  {
    numeroAtomico: 82,
    simbolo: 'Pb',
    elemento: 'Lead',
    massaAtomico: '207,2',
    fusao: '327,5',
    ebulicao: '1740,0',
  },
  {
    numeroAtomico: 83,
    simbolo: 'Bi',
    elemento: 'Bismuth',
    massaAtomico: '208,980',
    fusao: '271,3',
    ebulicao: '1560,0',
  },
  {
    numeroAtomico: 84,
    simbolo: 'Po',
    elemento: 'Polonium',
    massaAtomico: '209,0',
    fusao: '254,0',
    ebulicao: '962,0',
  },
  {
    numeroAtomico: 85,
    simbolo: 'At',
    elemento: 'Astatine',
    massaAtomico: '210,0',
    fusao: '302,0',
    ebulicao: '337,0',
  },
  {
    numeroAtomico: 86,
    simbolo: 'Rn',
    elemento: 'Radon',
    massaAtomico: '222,0',
    fusao: '202,0',
    ebulicao: '211,3',
  },
  {
    numeroAtomico: 87,
    simbolo: 'Fr',
    elemento: 'Francium',
    massaAtomico: '223,0',
    fusao: '300,0',
    ebulicao: '950,0',
  },
  {
    numeroAtomico: 88,
    simbolo: 'Ra',
    elemento: 'Radium',
    massaAtomico: '226,0',
    fusao: '973,0',
    ebulicao: '1413,0',
  },
  {
    numeroAtomico: 89,
    simbolo: 'Ac',
    elemento: 'Actinium',
    massaAtomico: '227,0',
    fusao: '1323,0',
    ebulicao: '3471,0',
  },
  {
    numeroAtomico: 90,
    simbolo: 'Th',
    elemento: 'Tório',
    massaAtomico: '232,038',
    fusao: '1750,0',
    ebulicao: '4876,0',
  },
  {
    numeroAtomico: 91,
    simbolo: 'Pa',
    elemento: 'Protactinium',
    massaAtomico: '231,0359',
    fusao: '1572,0',
    ebulicao: '4300,0',
  },
  {
    numeroAtomico: 92,
    simbolo: 'U',
    elemento: 'Urânio',
    massaAtomico: '238,0289',
    fusao: '1132,0',
    ebulicao: '3818,0',
  },
  {
    numeroAtomico: 93,
    simbolo: 'Np',
    elemento: 'Neptunium',
    massaAtomico: '237,0',
    fusao: '640,0',
    ebulicao: '3902,0',
  },
  {
    numeroAtomico: 94,
    simbolo: 'Pu',
    elemento: 'Plutônio',
    massaAtomico: '244,0',
    fusao: '640,0',
    ebulicao: '3235,0',
  },
  {
    numeroAtomico: 95,
    simbolo: 'Am',
    elemento: 'Amercio',
    massaAtomico: '243,0',
    fusao: '1176,0',
    ebulicao: '2011,0',
  },
  {
    numeroAtomico: 96,
    simbolo: 'Cm',
    elemento: 'Curium',
    massaAtomico: '247,0',
    fusao: '1340,0',
    ebulicao: '3110,0',
  },
  {
    numeroAtomico: 97,
    simbolo: 'Bk',
    elemento: 'Berkelio',
    massaAtomico: '247,0',
    fusao: '1259,0',
    ebulicao: 'n/d',
  },
  {
    numeroAtomico: 98,
    simbolo: 'Cf',
    elemento: 'Californium',
    massaAtomico: '251,0',
    fusao: '900,0',
    ebulicao: 'n/d',
  },
  {
    numeroAtomico: 99,
    simbolo: 'Es',
    elemento: 'Einstenio',
    massaAtomico: '252,0',
    fusao: 'n/d',
    ebulicao: 'n/d',
  },
  {
    numeroAtomico: 100,
    simbolo: 'Fm',
    elemento: 'Fermio',
    massaAtomico: '257,0',
    fusao: 'n/d',
    ebulicao: 'n/d',
  },
  {
    numeroAtomico: 101,
    simbolo: 'Md',
    elemento: 'Mendelevio',
    massaAtomico: '258,0',
    fusao: 'n/d',
    ebulicao: 'n/d',
  },
  {
    numeroAtomico: 102,
    simbolo: 'No',
    elemento: 'Nobelio',
    massaAtomico: '259,0',
    fusao: 'n/d',
    ebulicao: 'n/d',
  },
  {
    numeroAtomico: 103,
    simbolo: 'Lr',
    elemento: 'Lawrencio',
    massaAtomico: '262,0',
    fusao: 'n/d',
    ebulicao: 'n/d',
  },
  {
    numeroAtomico: 104,
    simbolo: 'Rf',
    elemento: 'Rutherfordio',
    massaAtomico: '267',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 105,
    simbolo: 'Db',
    elemento: 'Dubnio',
    massaAtomico: '268',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 106,
    simbolo: 'Sg',
    elemento: 'Seaborgio',
    massaAtomico: '271',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 107,
    simbolo: 'Bh',
    elemento: 'Bohrio',
    massaAtomico: '270',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 108,
    simbolo: 'Hs',
    elemento: 'Hassio',
    massaAtomico: '277',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 109,
    simbolo: 'Mt',
    elemento: 'Meitnerio',
    massaAtomico: '276',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 110,
    simbolo: 'Ds',
    elemento: 'Darmstadtio',
    massaAtomico: '281',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 111,
    simbolo: 'Rg',
    elemento: 'Roentgenio',
    massaAtomico: '280',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 112,
    simbolo: 'Cn',
    elemento: 'Copernicio',
    massaAtomico: '285',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 113,
    simbolo: 'Nh',
    elemento: 'Nihonio',
    massaAtomico: '284',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 114,
    simbolo: 'Fl',
    elemento: 'Flerovio',
    massaAtomico: '289',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 115,
    simbolo: 'Mc',
    elemento: 'Moscovio',
    massaAtomico: '288',
    fusao: null,
    ebulicao: null,
  },
  {
    numeroAtomico: 116,
    simbolo: 'Lv',
    elemento: 'Livermório',
    massaAtomico: '[293 ]',
    fusao: 'N/A',
    ebulicao: 'N/A',
  },
  {
    numeroAtomico: 117,
    simbolo: 'Ts',
    elemento: 'Ténnebroso',
    massaAtomico: '[ 294 ]',
    fusao: 'N/A',
    ebulicao: 'N/A',
  },
  {
    numeroAtomico: 118,
    simbolo: 'Og',
    elemento: 'Oganessón',
    massaAtomico: '[ 294 ]',
    fusao: 'N/A',
    ebulicao: 'N/A',
  },
];
